spring.application.name=servico-auditor-dlq

spring.datasource.url=jdbc:h2:mem:auditdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# AWS
cloud.aws.region.static=${aws.region:us-east-1}
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.stack.auto=false

# SQS
sqs.dlq.name=${SQS_DLQ_NAME}

logging.level.com.auditor.dlq=DEBUG
logging.level.io.awspring.cloud=INFO
logging.level.software.amazon.awssdk=INFO
